"""POST /api/v1/optimize — Submit a new portfolio optimization run.

Accepts optimization constraints, persists a pending run record to the
database, enqueues a Celery task for long-running quantum jobs, and returns
the run_id immediately. Progress is streamed via the WebSocket endpoint at
/ws/runs/{run_id}/progress.

Security hardening (Phase 3)
-----------------------------
- Rate limiting via ``slowapi`` (Redis-backed): 10 requests per minute per
  client IP.  This replaces the previous absence of any rate limiting on this
  endpoint.  The limit is intentionally conservative because each optimization
  run is compute-intensive (quantum jobs can take 60+ seconds).
- The ``request: Request`` parameter is required by ``slowapi`` to extract
  the client identifier for rate-limit tracking.
- ``ws_token`` is included in the response so the client can authenticate the
  WebSocket connection (implemented in Phase 2 / ``core/security.py``).
"""

import uuid

from fastapi import APIRouter, Request

from app.core.dependencies import DbDep
from app.core.logging import get_logger
from app.core.rate_limit import RATE_LIMIT_WRITE, limiter
from app.db.models import OptimizationRun
from app.schemas.requests import OptimizationRequest
from app.schemas.responses import OptimizationSubmitResponse


logger = get_logger(__name__)
router = APIRouter(tags=["optimization"])


@router.post(
    "/optimize",
    response_model=OptimizationSubmitResponse,
    status_code=202,
    summary="Submit portfolio optimization run",
    description=(
        "Accepts portfolio constraints and enqueues an optimization run. "
        "Persists a pending run record immediately so the client can poll "
        "for status. Returns a run_id immediately. Use the WebSocket endpoint "
        "/ws/runs/{run_id}/progress to stream real-time agent progress, or "
        "poll GET /api/v1/runs/{run_id}/status for lightweight status checks."
    ),
    responses={
        202: {"description": "Optimization run accepted and queued"},
        429: {"description": "Rate limit exceeded — too many optimization requests"},
    },
)
@limiter.limit(RATE_LIMIT_WRITE)
async def submit_optimization(
    request: Request,
    body: OptimizationRequest,
    db: DbDep,
) -> "OptimizationSubmitResponse":
    """Submit a new optimization run.

    The full agent graph (data fetch → classical opt → quantum opt →
    comparison → LLM explanation) is executed asynchronously via Celery.

    A pending ``OptimizationRun`` record is persisted to the database
    *before* the Celery task is dispatched. This guarantees that the record
    exists when the client immediately polls ``GET /api/v1/runs/{run_id}``
    or connects to the WebSocket.

    Args:
        request: FastAPI request object (required by slowapi rate limiter).
        body:    Optimization constraints (tickers, budget, run_quantum, etc.).
        db:      Injected async SQLAlchemy session.

    Returns:
        ``OptimizationSubmitResponse`` with ``run_id`` and optionally a
        ``ws_token`` for authenticating the WebSocket progress stream.

    Raises:
        HTTP 429: If the client has exceeded the rate limit (10/minute).
        HTTP 422: If the request body fails Pydantic validation.
    """
    run_id = str(uuid.uuid4())

    # ── Persist pending run record ────────────────────────────────────────────
    # Create the DB record first so the client can poll immediately after
    # receiving the 202 response.
    run = OptimizationRun(
        run_id=run_id,
        status="pending",
        tickers=body.tickers,
        budget=body.budget,
        request_params=body.model_dump(mode="json"),
    )
    db.add(run)
    await db.flush()  # Flush to DB within the current transaction

    logger.info(
        "optimization_submitted",
        run_id=run_id,
        tickers=body.tickers,
        budget=body.budget,
        run_quantum=body.run_quantum,
        num_tickers=len(body.tickers),
    )

    # ── Issue WebSocket auth token ────────────────────────────────────────────
    # Generate a short-lived HMAC token scoped to this run_id so the client
    # can authenticate the WebSocket connection without a full JWT stack.
    # The token is generated by core/security.py (Phase 2).
    ws_token: str | None = None
    try:
        from app.core.config import get_settings as _get_settings  # noqa: PLC0415
        from app.core.security import create_ws_token  # noqa: PLC0415

        _settings = _get_settings()
        ws_token = create_ws_token(run_id=run_id, secret_key=_settings.SECRET_KEY)
    except Exception as exc:
        # Non-fatal: the WebSocket endpoint will reject unauthenticated
        # connections, but the optimization run itself is unaffected.
        logger.warning(
            "ws_token_generation_failed",
            run_id=run_id,
            error=str(exc),
        )

    # ── Dispatch Celery task ──────────────────────────────────────────────────
    # Import lazily to avoid circular imports and to allow the worker module
    # to be developed independently.
    from app.workers.tasks import run_optimization_task  # noqa: PLC0415

    run_optimization_task.apply_async(
        kwargs={
            "run_id": run_id,
            "request_dict": body.model_dump(mode="json"),
        },
        task_id=run_id,
        queue="quantum" if body.run_quantum else "default",
    )

    return OptimizationSubmitResponse(run_id=run_id, ws_token=ws_token)
