"""SQLAlchemy ORM models for the Portfolio Optimizer.

Tables:
    optimization_runs — stores the full history of optimization runs,
                        including inputs, results, and status.

Design decisions:
    - Uses PostgreSQL-native UUID type for run_id to guarantee global uniqueness.
    - JSON columns store rich nested result objects (classical/quantum results,
      comparison summary) to avoid over-normalisation for this use case.
    - Denormalised Sharpe ratio columns (classical_sharpe, quantum_sharpe) allow
      efficient list queries without deserialising the full JSON blobs.
    - All timestamps are timezone-aware (UTC) to avoid ambiguity.
    - Check constraints enforce valid status values and non-negative budgets at
      the database level, providing a safety net beyond application validation.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models.

    All models that inherit from this base will share the same metadata
    object, which is used by Alembic for autogenerate support.
    """

    pass


class OptimizationRun(Base):
    """Stores the full lifecycle of a portfolio optimization run.

    Lifecycle:
        pending   → The run has been submitted but not yet picked up by a worker.
        running   → A Celery worker is actively executing the agent graph.
        completed → The agent graph finished successfully; results are populated.
        failed    → The agent graph encountered an unrecoverable error.

    Columns:
        id               — Auto-increment integer primary key (internal use only).
        run_id           — UUID string exposed in the API (indexed for fast lookup).
        status           — Run lifecycle state: pending | running | completed | failed.
        tickers          — JSON array of ticker symbols submitted by the user.
        budget           — Investment budget in USD (must be > 0).
        request_params   — Full serialised OptimizationRequest as JSON.
        classical_result — ClassicalResult as JSON (null until completed).
        quantum_result   — QuantumResult as JSON (null if run_quantum=False or pending).
        comparison       — ComparisonSummary as JSON (null until completed).
        llm_explanation  — LLM-generated natural language explanation (null until completed).
        classical_sharpe — Denormalised Sharpe ratio for efficient list queries.
        quantum_sharpe   — Denormalised quantum Sharpe ratio for efficient list queries.
        error_message    — Human-readable error description when status == failed.
        created_at       — UTC timestamp when the run was submitted.
        completed_at     — UTC timestamp when the run finished (null if not done).
    """

    __tablename__ = "optimization_runs"

    __table_args__ = (
        # Enforce valid status values at the DB level
        CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="ck_optimization_runs_status",
        ),
        # Budget must be positive
        CheckConstraint(
            "budget > 0",
            name="ck_optimization_runs_budget_positive",
        ),
        # Composite index for common list query: status + created_at DESC
        Index(
            "ix_optimization_runs_status_created_at",
            "status",
            "created_at",
        ),
    )

    # ── Primary key ──────────────────────────────────────────────────────────

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
        comment="Internal auto-increment primary key",
    )

    # ── Identity ─────────────────────────────────────────────────────────────

    run_id: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid.uuid4()),
        comment="UUID exposed in the API; generated by the application layer",
    )

    # ── Status ───────────────────────────────────────────────────────────────

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="pending",
        index=True,
        comment="Run lifecycle state: pending | running | completed | failed",
    )

    # ── Request inputs ───────────────────────────────────────────────────────

    tickers: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        comment="JSON array of ticker symbols (e.g. ['AAPL', 'MSFT'])",
    )
    budget: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Investment budget in USD",
    )
    request_params: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Full serialised OptimizationRequest payload",
    )

    # ── Results (populated when status == 'completed') ───────────────────────

    classical_result: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Serialised ClassicalResult from Markowitz MVO",
    )
    quantum_result: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Serialised QuantumResult (QAOA + VQE) — null if run_quantum=False",
    )
    comparison: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Serialised ComparisonSummary (classical vs quantum metrics)",
    )
    llm_explanation: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="LLM-generated natural language explanation of the results",
    )
    frontier_report: Mapped[dict | None] = mapped_column(
        JSON,
        nullable=True,
        comment=(
            "Serialised FrontierReport (efficient-frontier bundle) — "
            "null when the request did not enable the frontier sweep"
        ),
    )

    # ── Denormalised metrics for efficient list queries ───────────────────────

    classical_sharpe: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Denormalised classical Sharpe ratio for list query performance",
    )
    quantum_sharpe: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Denormalised quantum Sharpe ratio (QAOA preferred, else VQE)",
    )

    # ── Error handling ────────────────────────────────────────────────────────

    error_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human-readable error description when status == 'failed'",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="UTC timestamp when the run was submitted",
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp when the run finished (null if still in progress)",
    )

    # ── Helpers ───────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        return (
            f"<OptimizationRun "
            f"run_id={self.run_id!r} "
            f"status={self.status!r} "
            f"tickers={self.tickers!r}>"
        )

    def mark_running(self) -> None:
        """Transition the run to 'running' status."""
        self.status = "running"

    def mark_completed(self, completed_at: datetime | None = None) -> None:
        """Transition the run to 'completed' status.

        Args:
            completed_at: Completion timestamp. Defaults to current UTC time.
        """
        self.status = "completed"
        self.completed_at = completed_at or datetime.now(UTC)

    def mark_failed(
        self,
        error_message: str,
        completed_at: datetime | None = None,
    ) -> None:
        """Transition the run to 'failed' status.

        Args:
            error_message: Human-readable description of the failure.
            completed_at: Failure timestamp. Defaults to current UTC time.
        """
        self.status = "failed"
        self.error_message = error_message
        self.completed_at = completed_at or datetime.now(UTC)

    @property
    def is_terminal(self) -> bool:
        """Return True if the run is in a terminal state (completed or failed)."""
        return self.status in ("completed", "failed")

    @property
    def duration_seconds(self) -> float | None:
        """Return the run duration in seconds, or None if not yet completed."""
        if self.completed_at is None or self.created_at is None:
            return None
        # Ensure both datetimes are timezone-aware for subtraction
        created = self.created_at
        completed = self.completed_at
        if created.tzinfo is None:
            created = created.replace(tzinfo=UTC)
        if completed.tzinfo is None:
            completed = completed.replace(tzinfo=UTC)
        return (completed - created).total_seconds()
