"""Initial schema — create optimization_runs table.

Revision ID: 001
Revises: (none — this is the first migration)
Create Date: 2024-01-01 00:00:00.000000 UTC

This migration creates the core ``optimization_runs`` table that stores
the full lifecycle of every portfolio optimization request, including:
  - Input parameters (tickers, budget, constraints)
  - Classical Markowitz MVO results (JSON)
  - Quantum QAOA/VQE results (JSON)
  - Side-by-side comparison summary (JSON)
  - LLM-generated explanation text
  - Denormalised Sharpe ratios for efficient list queries
  - Status tracking (pending → running → completed | failed)
  - Timestamps (created_at, completed_at)

Indexes created:
  - ix_optimization_runs_run_id       — unique, for API lookups by UUID
  - ix_optimization_runs_status       — for filtering by run state
  - ix_optimization_runs_created_at   — for chronological ordering
  - ix_optimization_runs_status_created_at — composite for list queries

Check constraints:
  - ck_optimization_runs_status         — valid status values
  - ck_optimization_runs_budget_positive — budget must be > 0
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the optimization_runs table with all indexes and constraints."""

    op.create_table(
        "optimization_runs",

        # ── Primary key ───────────────────────────────────────────────────────
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Internal auto-increment primary key",
        ),

        # ── Identity ──────────────────────────────────────────────────────────
        sa.Column(
            "run_id",
            sa.String(length=36),
            nullable=False,
            comment="UUID exposed in the API; generated by the application layer",
        ),

        # ── Status ────────────────────────────────────────────────────────────
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
            comment="Run lifecycle state: pending | running | completed | failed",
        ),

        # ── Request inputs ────────────────────────────────────────────────────
        sa.Column(
            "tickers",
            sa.JSON(),
            nullable=False,
            comment="JSON array of ticker symbols (e.g. ['AAPL', 'MSFT'])",
        ),
        sa.Column(
            "budget",
            sa.Float(),
            nullable=False,
            comment="Investment budget in USD",
        ),
        sa.Column(
            "request_params",
            sa.JSON(),
            nullable=False,
            server_default="{}",
            comment="Full serialised OptimizationRequest payload",
        ),

        # ── Results ───────────────────────────────────────────────────────────
        sa.Column(
            "classical_result",
            sa.JSON(),
            nullable=True,
            comment="Serialised ClassicalResult from Markowitz MVO",
        ),
        sa.Column(
            "quantum_result",
            sa.JSON(),
            nullable=True,
            comment="Serialised QuantumResult (QAOA + VQE)",
        ),
        sa.Column(
            "comparison",
            sa.JSON(),
            nullable=True,
            comment="Serialised ComparisonSummary (classical vs quantum metrics)",
        ),
        sa.Column(
            "llm_explanation",
            sa.Text(),
            nullable=True,
            comment="LLM-generated natural language explanation of the results",
        ),

        # ── Denormalised metrics ───────────────────────────────────────────────
        sa.Column(
            "classical_sharpe",
            sa.Float(),
            nullable=True,
            comment="Denormalised classical Sharpe ratio for list query performance",
        ),
        sa.Column(
            "quantum_sharpe",
            sa.Float(),
            nullable=True,
            comment="Denormalised quantum Sharpe ratio (QAOA preferred, else VQE)",
        ),

        # ── Error handling ────────────────────────────────────────────────────
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Human-readable error description when status == 'failed'",
        ),

        # ── Timestamps ────────────────────────────────────────────────────────
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the run was submitted",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC timestamp when the run finished",
        ),

        # ── Constraints ───────────────────────────────────────────────────────
        sa.PrimaryKeyConstraint("id", name="pk_optimization_runs"),
        sa.UniqueConstraint("run_id", name="uq_optimization_runs_run_id"),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="ck_optimization_runs_status",
        ),
        sa.CheckConstraint(
            "budget > 0",
            name="ck_optimization_runs_budget_positive",
        ),
    )

    # ── Indexes ───────────────────────────────────────────────────────────────

    # Unique index on run_id for fast API lookups by UUID
    op.create_index(
        op.f("ix_optimization_runs_run_id"),
        "optimization_runs",
        ["run_id"],
        unique=True,
    )

    # Index on status for filtering by run state (e.g. list pending runs)
    op.create_index(
        op.f("ix_optimization_runs_status"),
        "optimization_runs",
        ["status"],
        unique=False,
    )

    # Index on created_at for chronological ordering in list queries
    op.create_index(
        op.f("ix_optimization_runs_created_at"),
        "optimization_runs",
        ["created_at"],
        unique=False,
    )

    # Composite index for the most common list query pattern:
    # WHERE status = ? ORDER BY created_at DESC
    op.create_index(
        "ix_optimization_runs_status_created_at",
        "optimization_runs",
        ["status", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the optimization_runs table and all associated indexes."""

    # Drop indexes first (required before dropping the table in some DBs,
    # though PostgreSQL handles this automatically via CASCADE)
    op.drop_index(
        "ix_optimization_runs_status_created_at",
        table_name="optimization_runs",
    )
    op.drop_index(
        op.f("ix_optimization_runs_created_at"),
        table_name="optimization_runs",
    )
    op.drop_index(
        op.f("ix_optimization_runs_status"),
        table_name="optimization_runs",
    )
    op.drop_index(
        op.f("ix_optimization_runs_run_id"),
        table_name="optimization_runs",
    )

    op.drop_table("optimization_runs")
