"""Add chat_sessions table for the chat assistant feature.

Revision ID: 003
Revises: 002
Create Date: 2026-06-16 00:00:00.000000 UTC

This migration introduces the ``chat_sessions`` table that stores
multi-turn chat conversations used by the chat assistant to collect
portfolio optimization parameters via natural language slot filling.

Table design:
    - ``session_id``      — UUID string (36 chars) exposed in the API.
    - ``status``          — Lifecycle state: collecting | pending_confirmation
                            | confirmed | expired.
    - ``messages``        — Full conversation history as a JSON array of
                            ``{"role": "user"|"assistant", "content": "..."}``
                            objects.
    - ``extracted_slots`` — Partial or complete OptimizationRequest fields
                            extracted by the LLM, stored as a JSON object.
    - ``run_id``          — Nullable FK to ``optimization_runs.run_id``;
                            set when the session is confirmed.
    - ``created_at``      — UTC creation timestamp.
    - ``updated_at``      — UTC last-modified timestamp.
    - ``expires_at``      — UTC expiry timestamp (created_at + TTL).

Indexes created:
    - ix_chat_sessions_session_id  — Unique; primary API lookup key.
    - ix_chat_sessions_status      — Filter by lifecycle state.
    - ix_chat_sessions_expires_at  — Efficient expiry sweep queries.
    - ix_chat_sessions_run_id      — Join to optimization_runs.

Check constraints:
    - ck_chat_sessions_status              — Valid status values.
    - ck_chat_sessions_expires_after_created — expires_at > created_at.

Foreign keys:
    - fk_chat_sessions_run_id → optimization_runs.run_id (ON DELETE SET NULL)

Backward compatibility:
    - This is a purely additive migration; existing tables are unaffected.
    - The ``optimization_runs`` table gains no new columns; the relationship
      is expressed only via the FK on ``chat_sessions``.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the chat_sessions table with all indexes and constraints."""

    op.create_table(
        "chat_sessions",

        # ── Primary key ───────────────────────────────────────────────────────
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Internal auto-increment primary key",
        ),

        # ── Identity ──────────────────────────────────────────────────────────
        sa.Column(
            "session_id",
            sa.String(length=36),
            nullable=False,
            comment="UUID exposed in the API; generated by the application layer",
        ),

        # ── Status ────────────────────────────────────────────────────────────
        sa.Column(
            "status",
            sa.String(length=25),
            nullable=False,
            server_default="collecting",
            comment=(
                "Session lifecycle state: "
                "collecting | pending_confirmation | confirmed | expired"
            ),
        ),

        # ── Conversation data ─────────────────────────────────────────────────
        sa.Column(
            "messages",
            sa.JSON(),
            nullable=False,
            server_default="[]",
            comment=(
                'Ordered list of conversation turns: '
                '[{"role": "user"|"assistant", "content": "..."}]'
            ),
        ),
        sa.Column(
            "extracted_slots",
            sa.JSON(),
            nullable=True,
            comment=(
                "Partial or complete OptimizationRequest fields extracted by the LLM. "
                "Null until the first successful extraction turn."
            ),
        ),

        # ── Link to optimization run ──────────────────────────────────────────
        sa.Column(
            "run_id",
            sa.String(length=36),
            nullable=True,
            comment=(
                "UUID of the dispatched OptimizationRun. "
                "Null until the session is confirmed."
            ),
        ),

        # ── Timestamps ────────────────────────────────────────────────────────
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the session was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp of the last message or status change",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment=(
                "UTC timestamp after which the session is considered expired. "
                "Set to created_at + TTL (default 24 h) on creation."
            ),
        ),

        # ── Constraints ───────────────────────────────────────────────────────
        sa.PrimaryKeyConstraint("id", name="pk_chat_sessions"),
        sa.UniqueConstraint("session_id", name="uq_chat_sessions_session_id"),
        sa.CheckConstraint(
            "status IN ('collecting', 'pending_confirmation', 'confirmed', 'expired')",
            name="ck_chat_sessions_status",
        ),
        sa.CheckConstraint(
            "expires_at > created_at",
            name="ck_chat_sessions_expires_after_created",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["optimization_runs.run_id"],
            name="fk_chat_sessions_run_id",
            ondelete="SET NULL",
        ),
    )

    # ── Indexes ───────────────────────────────────────────────────────────────

    # Unique index on session_id for fast API lookups by UUID
    op.create_index(
        "ix_chat_sessions_session_id",
        "chat_sessions",
        ["session_id"],
        unique=True,
    )

    # Index on status for filtering by lifecycle state
    op.create_index(
        "ix_chat_sessions_status",
        "chat_sessions",
        ["status"],
        unique=False,
    )

    # Index on expires_at for efficient expiry sweep queries
    op.create_index(
        "ix_chat_sessions_expires_at",
        "chat_sessions",
        ["expires_at"],
        unique=False,
    )

    # Index on run_id for joining to optimization_runs
    op.create_index(
        "ix_chat_sessions_run_id",
        "chat_sessions",
        ["run_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the chat_sessions table and all associated indexes."""

    # Drop indexes first (belt-and-suspenders; PostgreSQL drops them with the table)
    op.drop_index("ix_chat_sessions_run_id", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_expires_at", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_status", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_session_id", table_name="chat_sessions")

    op.drop_table("chat_sessions")
